# Generated by Django 5.2.5 on 2025-08-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('supermercado', models.CharField(max_length=50)),
            ],
        ),
    ]
